const state = {
  expandedCategoryId: null,

  categories: [
    {
      name: "motorisation",
      id: 1,
      class: "motoryzacja",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/motoryzacja-5-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Samochody Osobowe",
          id: 1,
          link: "/cars",
          code: "passengerCars",
        },
        {
          name: "Części Samochodowe",
          id: 2,
          link: "www.wikipedia.com",
          code: "carParts",
        },
        {
          name: "Pozostała Motoryzacja",
          id: 3,
          link: "www.wikipedia.com",
          code: "othersMoto",
        },
        {
          name: "Sprzęt Car Audio",
          id: 4,
          link: "www.wikipedia.com",
          code: "carAudio",
        },
        {
          name: "Motocykle i Skutery",
          id: 5,
          link: "www.wikipedia.com",
          code: "motorbikes",
        },
        {
          name: "Opony i Felgi",
          id: 6,
          link: "www.wikipedia.com",
          code: "tiresAndWheels",
        },
        {
          name: "Samochody Dostawcze",
          id: 7,
          link: "www.wikipedia.com",
          code: "vans",
        },
        {
          name: "Ubezpieczenia OC/AC",
          id: 8,
          link: "www.wikipedia.com",
          code: "insurance",
        },
        {
          name: "Części Motocyklowe",
          id: 9,
          link: "www.wikipedia.com",
          code: "motorbikeParts",
        },
        {
          name: "Przyczepy i Pojazdy Użytkowe",
          id: 10,
          link: "www.wikipedia.com",
          code: "trailers",
        },
      ],
    },
    {
      name: "estate",
      id: 2,
      class: "nieruchomosci",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/nieruchomosci-3-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Mieszkania",
          id: 1,
          link: "www.wikipedia.com",
          code: "flats",
        },
        {
          name: "Garaże i Parkingi",
          id: 2,
          link: "www.wikipedia.com",
          code: "garagesAndParking",
        },
        {
          name: "Pozostałe Nieruchomości",
          id: 3,
          link: "www.wikipedia.com",
          code: "othersEstate",
        },
        { name: "Domy", id: 4, link: "www.wikipedia.com", code: "houses" },
        { name: "Ogród", id: 5, link: "www.wikipedia.com", code: "garden" },
        {
          name: "Biura i Lokale",
          id: 6,
          link: "www.wikipedia.com",
          code: "offices",
        },
        {
          name: "Stancje i Pokoje",
          id: 7,
          link: "www.wikipedia.com",
          code: "rooms",
        },
        {
          name: "Hale i Magazyny",
          id: 8,
          link: "www.wikipedia.com",
          code: "warehouses",
        },
        {
          name: "Kwatery Pracownicze",
          id: 9,
          link: "www.wikipedia.com",
          code: "workersAccommodation",
        },
        { name: "Działki", id: 10, link: "www.wikipedia.com", code: "land" },
      ],
    },
    {
      name: "jobs",
      id: 3,
      class: "praca",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/praca-4-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Administracja biurowa",
          id: 1,
          link: "www.wikipedia.com",
          code: "administration",
        },
        {
          name: "Budowa/remonty",
          id: 2,
          link: "www.wikipedia.com",
          code: "construction",
        },
        {
          name: "Call center, konsultant telefoniczny",
          id: 3,
          link: "www.wikipedia.com",
          code: "callCenter",
        },
        {
          name: "E-commerce (handel internetowy)",
          id: 4,
          link: "www.wikipedia.com",
          code: "eCommerce",
        },
        {
          name: "Edukacja",
          id: 5,
          link: "www.wikipedia.com",
          code: "education",
        },
        {
          name: "Finanse / księgowość",
          id: 6,
          link: "www.wikipedia.com",
          code: "finance",
        },
        {
          name: "Franczyza / Własna firma",
          id: 7,
          link: "www.wikipedia.com",
          code: "franchise",
        },
        {
          name: "Fryzjerstwo, kosmetyka",
          id: 8,
          link: "www.wikipedia.com",
          code: "hairdressing",
        },
        {
          name: "Gastronomia",
          id: 9,
          link: "www.wikipedia.com",
          code: "hospitality",
        },
        { name: "HR", id: 10, link: "www.wikipedia.com", code: "hr" },
        { name: "Hostessa", id: 11, link: "www.wikipedia.com", code: "host" },
        {
          name: "Hotelarstwo",
          id: 12,
          link: "www.wikipedia.com",
          code: "hotels",
        },
      ],
    },
    {
      name: "home",
      id: 4,
      class: "dom",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/dom-ogrod-628-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Meble", id: 1, link: "www.wikipedia.com", code: "furniture" },
        {
          name: "Zdrowie",
          id: 2,
          link: "www.wikipedia.com",
          code: "wellBeing",
        },
        {
          name: "Ogród",
          id: 3,
          link: "www.wikipedia.com",
          code: "garden",
        },
        {
          name: "Narzędzia",
          id: 4,
          link: "www.wikipedia.com",
          code: "tools",
        },
        {
          name: "Materiały Budowlane",
          id: 5,
          link: "www.wikipedia.com",
          code: "buildingMaterials",
        },
        {
          name: "Ogrzewanie",
          id: 6,
          link: "www.wikipedia.com",
          code: "heating",
        },
        {
          name: "Wyposażenie Wnętrz",
          id: 7,
          link: "www.wikipedia.com",
          code: "interior",
        },
        {
          name: "Pozostałe Dom i Ogród",
          id: 8,
          link: "www.wikipedia.com",
          code: "othersHome",
        },
        { name: "Sprzęt AGD", id: 9, link: "www.wikipedia.com", code: "agd" },
      ],
    },
    {
      name: "electronics",
      id: 5,
      class: "elektronika",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/elektronika-99-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Akcesoria Telefoniczne",
          id: 1,
          link: "www.wikipedia.com",
          code: "phoneAccessories",
        },
        {
          name: "Fotografia",
          id: 2,
          link: "www.wikipedia.com",
          code: "photography",
        },
        {
          name: "Gry i Konsole",
          id: 3,
          link: "www.wikipedia.com",
          code: "games",
        },
        {
          name: "Komputery",
          id: 4,
          link: "www.wikipedia.com",
          code: "computers",
        },
        {
          name: "Smartwatche i Opaski",
          id: 5,
          link: "www.wikipedia.com",
          code: "smartwatches",
        },
        { name: "Sprzęt AGD", id: 6, link: "www.wikipedia.com", code: "agd" },
        {
          name: "Sprzęt audio",
          id: 7,
          link: "www.wikipedia.com",
          code: "audio",
        },
        {
          name: "Sprzęt video",
          id: 8,
          link: "www.wikipedia.com",
          code: "video",
        },
        {
          name: "Telefony",
          id: 9,
          link: "www.wikipedia.com",
          code: "mobilePhones",
        },
        { name: "TV", id: 10, link: "www.wikipedia.com", code: "tv" },
        {
          name: "Pozostała Elektronika",
          id: 11,
          link: "www.wikipedia.com",
          code: "othersElectronics",
        },
      ],
    },
    {
      name: "fashion",
      id: 6,
      class: "moda",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/moda-87-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Ubrania", id: 1, link: "www.wikipedia.com", code: "clothes" },
        { name: "Buty", id: 2, link: "www.wikipedia.com", code: "shoes" },
        {
          name: "Bielizna",
          id: 3,
          link: "www.wikipedia.com",
          code: "underwear",
        },
        {
          name: "Odzież ciążowa",
          id: 4,
          link: "www.wikipedia.com",
          code: "maternity",
        },
        {
          name: "Dodatki",
          id: 5,
          link: "www.wikipedia.com",
          code: "fashionAccessories",
        },
        {
          name: "Biżuteria",
          id: 6,
          link: "www.wikipedia.com",
          code: "jewelry",
        },
        { name: "Torebki", id: 7, link: "www.wikipedia.com", code: "handbags" },
        { name: "Zegarki", id: 8, link: "www.wikipedia.com", code: "watches" },
        {
          name: "Kosmetyki i Perfumy",
          id: 9,
          link: "www.wikipedia.com",
          code: "cosmetics",
        },
        {
          name: "Pozostała Moda",
          id: 10,
          link: "www.wikipedia.com",
          code: "othersFashion",
        },
        {
          name: "Moda Ślubna",
          id: 11,
          link: "www.wikipedia.com",
          code: "weddingFashion",
        },
        {
          name: "Akcesoria Ślubne",
          id: 12,
          link: "www.wikipedia.com",
          code: "weddingAccessories",
        },
      ],
    },
    {
      name: "agriculture",
      id: 7,
      class: "rolnictwo",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/rolnictwo-757-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Ciągniki",
          id: 1,
          link: "www.wikipedia.com",
          code: "tractors",
        },
        {
          name: "Maszyny rolnicze",
          id: 2,
          link: "www.wikipedia.com",
          code: "agriculturalMachines",
        },
        {
          name: "Przyczepy",
          id: 3,
          link: "www.wikipedia.com",
          code: "agricultureTrailer",
        },
        {
          name: "Części do maszyn rolniczych",
          id: 4,
          link: "www.wikipedia.com",
          code: "agricultureParts",
        },
        {
          name: "Opony rolnicze",
          id: 5,
          link: "www.wikipedia.com",
          code: "agricultureTires",
        },
        {
          name: "Produkty rolne",
          id: 6,
          link: "www.wikipedia.com",
          code: "agricultureProducts",
        },
        {
          name: "Giełda zwierząt",
          id: 7,
          link: "www.wikipedia.com",
          code: "agricultureAnimals",
        },
        { name: "Ryneczek", id: 8, link: "www.wikipedia.com", code: "market" },
        {
          name: "Pozostałe rolnicze",
          id: 9,
          link: "www.wikipedia.com",
          code: "othersAgriculture",
        },
      ],
    },
    {
      name: "animals",
      id: 8,
      class: "zwierzeta",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/zwierzeta-103-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Psy", id: 1, link: "www.wikipedia.com", code: "dogs" },
        { name: "Koty", id: 2, link: "www.wikipedia.com", code: "cats" },
        {
          name: "Ptaki",
          id: 3,
          link: "www.wikipedia.com",
          code: "birds",
        },
        {
          name: "Gryzonie i Króliki",
          id: 4,
          link: "www.wikipedia.com",
          code: "rodents",
        },
        { name: "Konie", id: 5, link: "www.wikipedia.com", code: "horses" },
        {
          name: "Akwarystyka",
          id: 6,
          link: "www.wikipedia.com",
          code: "fishKeeping",
        },
        {
          name: "Pozostałe zwierzęta",
          id: 7,
          link: "www.wikipedia.com",
          code: "othersAnimals",
        },
        {
          name: "Akcesoria dla zwierząt",
          id: 8,
          link: "www.wikipedia.com",
          code: "animalAccessories",
        },
        {
          name: "Zaginione i Znalezione",
          id: 9,
          link: "www.wikipedia.com",
          code: "lostAndFound",
        },
      ],
    },
    {
      name: "children",
      id: 9,
      class: "dzieci",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/dla-dzieci-88-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Zabawki", id: 1, link: "www.wikipedia.com", code: "toys" },
        {
          name: "Wózki dziecięce",
          id: 2,
          link: "www.wikipedia.com",
          code: "buggies",
        },
        {
          name: "Akcesoria dla niemowląt",
          id: 3,
          link: "www.wikipedia.com",
          code: "infantAccessories",
        },
        {
          name: "Foteliki - Nosidełka",
          id: 4,
          link: "www.wikipedia.com",
          code: "seats",
        },
        {
          name: "Ubranka dla dzieci",
          id: 5,
          link: "www.wikipedia.com",
          code: "childrenClothing",
        },
        {
          name: "Buciki",
          id: 6,
          link: "www.wikipedia.com",
          code: "childrenShoes",
        },
        {
          name: "Meble dla dzieci",
          id: 7,
          link: "www.wikipedia.com",
          code: "childrenFurniture",
        },
        {
          name: "Pozostałe dla dzieci",
          id: 8,
          link: "www.wikipedia.com",
          code: "othersChildren",
        },
      ],
    },
    {
      name: "sport",
      id: 10,
      class: "sport",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/sport-hobby-767-2x.png",
      link: "/cars",
      subCategories: [
        {
          name: "Akcesoria jeździeckie",
          id: 1,
          link: "www.wikipedia.com",
          code: "ridingAccessories",
        },
        { name: "Bilety", id: 2, link: "www.wikipedia.com", code: "tickets" },
        {
          name: "Fitness",
          id: 3,
          link: "www.wikipedia.com",
          code: "fitness",
        },
        {
          name: "Gry planszowe",
          id: 4,
          link: "www.wikipedia.com",
          code: "boardGames",
        },
        {
          name: "Kolekcje",
          id: 5,
          link: "www.wikipedia.com",
          code: "collections",
        },
        {
          name: "Militaria",
          id: 6,
          link: "www.wikipedia.com",
          code: "militaries",
        },
        {
          name: "Obuwie sportowe",
          id: 7,
          link: "www.wikipedia.com",
          code: "sportShoes",
        },
        {
          name: "Odzież sportowa",
          id: 8,
          link: "www.wikipedia.com",
          code: "sportClothing",
        },
        { name: "Rowery", id: 9, link: "www.wikipedia.com", code: "bikes" },
        { name: "Skating", id: 10, link: "www.wikipedia.com", code: "skating" },
        {
          name: "Społeczność",
          id: 11,
          link: "www.wikipedia.com",
          code: "community",
        },
        {
          name: "Sporty wodne",
          id: 12,
          link: "www.wikipedia.com",
          code: "waterSports",
        },
        {
          name: "Sporty zimowe",
          id: 13,
          link: "www.wikipedia.com",
          code: "winterSports",
        },
        {
          name: "Turystyka",
          id: 14,
          link: "www.wikipedia.com",
          code: "tourism",
        },
        {
          name: "Wędkarstwo",
          id: 15,
          link: "www.wikipedia.com",
          code: "fishing",
        },
        {
          name: "Pozostały Sport i Hobby",
          id: 16,
          link: "www.wikipedia.com",
          code: "otherSports",
        },
      ],
    },
    {
      name: "music",
      id: 11,
      class: "muzyka",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/muzyka-edukacja-751-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Książki", id: 1, link: "www.wikipedia.com", code: "books" },
        { name: "Muzyka", id: 2, link: "www.wikipedia.com", code: "music" },
        {
          name: "Filmy",
          id: 3,
          link: "www.wikipedia.com",
          code: "films",
        },
        {
          name: "Instrumenty",
          id: 4,
          link: "www.wikipedia.com",
          code: "instruments",
        },
        {
          name: "Materiały językowe",
          id: 5,
          link: "www.wikipedia.com",
          code: "languageResources",
        },
        {
          name: "Pozostała Muzyka i Edukacja",
          id: 6,
          link: "www.wikipedia.com",
          code: "othersMusic",
        },
      ],
    },
    {
      name: "services",
      id: 12,
      class: "uslugi",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/uslugi-firmy-619-2x.png",
      link: "/cars",
      subCategories: [
        { name: "Usługi", id: 1, link: "www.wikipedia.com", code: "services" },
        {
          name: "Wyposażenie firm",
          id: 2,
          link: "www.wikipedia.com",
          code: "businessEquipment",
        },
        {
          name: "Usługi ślubne",
          id: 3,
          link: "www.wikipedia.com",
          code: "weddingServices",
        },
        {
          name: "Budowa i Remont",
          id: 4,
          link: "www.wikipedia.com",
          code: "constructionAndMaintenance",
        },
        {
          name: "Korepetycje",
          id: 5,
          link: "www.wikipedia.com",
          code: "privateLessons",
        },
        {
          name: "Kursy i Warsztaty",
          id: 6,
          link: "www.wikipedia.com",
          code: "courses",
        },
        {
          name: "Meble na wymiar",
          id: 7,
          link: "www.wikipedia.com",
          code: "furnishing",
        },
        { name: "Muzycy", id: 8, link: "www.wikipedia.com", code: "musicians" },
        {
          name: "Obsługa imprez",
          id: 9,
          link: "www.wikipedia.com",
          code: "events",
        },
        {
          name: "Serwis RTV/AGD",
          id: 10,
          link: "www.wikipedia.com",
          code: "rtvAgdRepairs",
        },
        {
          name: "Sprzątanie",
          id: 11,
          link: "www.wikipedia.com",
          code: "cleaning",
        },
        {
          name: "Tłumaczenia",
          id: 12,
          link: "www.wikipedia.com",
          code: "translation",
        },
        {
          name: "Usługi dla zwierząt",
          id: 13,
          link: "www.wikipedia.com",
          code: "animalServices",
        },
        {
          name: "Usługi finansowe",
          id: 14,
          link: "www.wikipedia.com",
          code: "financialServices",
        },
        {
          name: "Usługi informatyczne",
          id: 15,
          link: "www.wikipedia.com",
          code: "it",
        },
        {
          name: "Usługi kosmetyczne",
          id: 16,
          link: "www.wikipedia.com",
          code: "cosmeticServices",
        },
        {
          name: "Usługi motoryzacyjne",
          id: 17,
          link: "www.wikipedia.com",
          code: "motoServices",
        },
        {
          name: "Usługi ogrodnicze",
          id: 18,
          link: "www.wikipedia.com",
          code: "gardenServices",
        },
        {
          name: "Usługi reklamowe",
          id: 19,
          link: "www.wikipedia.com",
          code: "advertServices",
        },
        {
          name: "Usługi transportowe",
          id: 20,
          link: "www.wikipedia.com",
          code: "transportServices",
        },
        {
          name: "Usługi zdrowotne",
          id: 21,
          link: "www.wikipedia.com",
          code: "healthServices",
        },
        {
          name: "Pozostałe usługi",
          id: 22,
          link: "www.wikipedia.com",
          code: "otherServices",
        },
      ],
    },
    {
      name: "accomodation",
      id: 13,
      class: "noclegi",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/noclegi-1816-2x.png",
      link: "/cars",
    },
    {
      name: "freebies",
      id: 14,
      class: "darmo",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/oddam-za-darmo-1151-2x.png",
      link: "/cars",
    },
    {
      name: "swap",
      id: 15,
      class: "zamienie",
      src: "https://categories.olxcdn.com/assets/categories/olxpl/zamienie-1153-2x.png",
      link: "/cars",
    },
    {
      name: "delivery",
      id: 16,
      class: "dostawca",
      src: "https://categories.olxcdn.com/assets/promo/olxpl/a-praca2911-1x.png",
      link: "/cars",
    },
    {
      name: "mountainHouse",
      id: 17,
      class: "domek",
      src: "https://categories.olxcdn.com/assets/promo/olxpl/b-uslugi0112-1x.png",
      link: "/cars",
    },
    {
      name: "phones",
      id: 18,
      class: "telefony",
      src: "https://categories.olxcdn.com/assets/promo/olxpl/c-telefony2711-1x.png",
      link: "/cars",
    },
  ],
};

const getters = {
  getExpandedCategoryId: (state) => {
    return state.expandedCategoryId;
  },

  getCategories: (state) => {
    return state.categories;
  },
};

const mutations = {
  SET_EXPANDED_CATEGORY_ID(state, expandedCategoryId) {
    state.expandedCategoryId = expandedCategoryId;
  },
};

const actions = {
  setExpandedCategoryId({ commit }, expandedCategoryId) {
    commit("SET_EXPANDED_CATEGORY_ID", expandedCategoryId);
  },
};

export default {
  namespaced: true,
  state,
  mutations,
  getters,
  actions,
};
